### DISCUSSION TITLE
quickstart notes

### DISCUSSION THREAD

**Discussion by PFC-developer** [strangelove-ventures/cosmos-operator#334] [General]
so firstly.
thank you for all the work you've done.

I classify myself as a k8s newbie, but i'm trying to follow best practices, and have installed flux, and do deployments to it via github PR's commits etc.

I am trying this on a kubeadm cluster, not GKE

# generating the manifests
the
```
make deploy ...
```
appears to just deploy directly

I assume I can just add it to my regular manifests and let it handle it, instead of it just deploying it over.

does
```
make manifests
```
do what I require?
it appears I just need the first line from the deploy makefile as well.
```cd config/manager && $(KUSTOMIZE) edit set image controller=${IMG}```

#  storage class

you may need to specify that it needs to be resizable here.

**Comment by PFC-developer** [comment]
and I presume I can just run it 'as-is', and don't need to change anything to my own artifact repos etc.

**Comment by DavidNix** [comment]
Can you clarify and add specifics what your goal is? To deploy via a Kustomization using FluxCD?

**Comment by PFC-developer** [comment]
yes. ideally via FluxCD.

It appears that the makefile creates a set of config files, and then deploys them to the cluster. 

my preference is to generate the config files, and just check them in, and let flux deploy/reconfigure etc, and have everything in a single place, managed by PR etc.

**Comment by DavidNix** [comment]
The `make` commands are mostly for local development. Our documentation needs improvement around deploying the operator. We also need a Helm Chart at some point (can't commit to timeline). 

For Flux, I recommend a Kustomization with Gitrepo pointed to the operator release tag you want. The kustomize is already present in the repo. No need to generate it. But you do need to set the image and git ref. And make sure they match.

Examples:

Note - we are using an older version of flux.

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cosmos-operator
  namespace: flux-system
spec:
  force: true
  images:
  - name: ghcr.io/strangelove-ventures/cosmos-operator
    newTag: v0.16.0 # Note the tag

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cosmos-operator
  namespace: flux-system
spec:
  gitImplementation: go-git
  ignore: |
    # exclude all
    /*
    # include kustomize files only
    !/config
  interval: 5m
  ref:
    tag: v0.16.0 # Note the tag
  timeout: 60s
  url: https://github.com/strangelove-ventures/cosmos-operator
```

We also use Flux at Strangelove and this is the exact strategy we use. We've used it many months with no issue.
