### DISCUSSION TITLE
demonstration/example of setting up RPC ports via ingress would be great

### DISCUSSION THREAD

**Discussion by PFC-developer** [strangelove-ventures/cosmos-operator#337] [Q&A] [answered]
hi.
It would be great to get an 'howto' to setup the rpc ports to use a ingress-nginx service instead of nodeport.

or potentially stuff like certmanager/exetrnal-dns to automatically assign it a TLS certificate and hostname to a 'nodeport'

**Comment by DavidNix** [comment, marked as answer]
General support for cert-manager/external-dns and ingresses is out of scope here. There are many great articles out there if you need help with those.

Many ingress controllers rely on custom annotations on the ingress itself and/or the corresponding service(s). 

The operator creates a service for all endpoints named `<my-fullnode-name>-rpc`. You can modify this service. Typically, you want the Ingress to map to this service.

```sh
❯ kubectl explain cosmosfullnode.spec.service.rpcTemplate

KIND:     CosmosFullNode
VERSION:  cosmos.strange.love/v1

RESOURCE: rpcTemplate <Object>

DESCRIPTION:
     Overrides for the single RPC service.

FIELDS:
   externalTrafficPolicy        <string>
     Sets endpoint and routing behavior. See:
     https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#caveats-and-limitations-when-preserving-source-ips
     If not set, defaults to "Cluster".

   metadata     <Object>
     Metadata is a subset of k8s object metadata.

   type <string>
     Describes ingress methods for a service. If not set, defaults to
     "ClusterIP".
```

```yaml
# Example using Google's ingress controller
apiVersion: cosmos.strange.love/v1
kind: CosmosFullNode
metadata:
  name: cosmoshub
spec:
  service:
    rpcTemplate:
      metadata:
        annotations:
          cloud.google.com/app-protocols: '{"grpc": "HTTP2"}'
          cloud.google.com/backend-config: '{"default": "some-lb-backend"}'
          cloud.google.com/neg: '{"ingress": true}'
```

In the above example, operator creates a service `cosmoshub-rpc` in the CosmosFullNode's namespace.

Or you can create your own service. The operator assigns stable labels to each pod.
