### ISSUE TITLE
CosmosFullNode upgrade should be schedule-able at some future block height

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/cosmos-operator#15]
Scenario: A human doesn't need to be present for the upgrade
  When something goes wrong
  then a human is alerted

---

"This is gonna be the biggest Quality-of-Life enhancement for the infra team" — @agouin 

---

```[tasklist]
- [ ] break into smaller stories
- [ ] what does cosmovisor do? what else do we need to write?
```

---

This probably needs to be a new CRD with a separate controller such as: CosmosFullNodeUpgrade or the longer CosmosFullNodeScheduledUpgrade. 

Therefore, it's a large effort. https://github.com/backube/snapscheduler may be good inspiration for how to properly schedule actions in the future. 

The problem is it's toil to schedule at an exact time especially for chain halt upgrades. 

The CRD likely needs to distinguish between chain halt and "regular" upgrades with the ability to get height from chains.

**Comment by agouin** [comment]
Thoughts on this building on top of @DavidNix idea for requiring block ranges/versions to be declared in config:
Before:
```yaml
      podTemplate:
        image: ghcr.io/strangelove-ventures/heighliner/chain:v2.0.0
```

After:
```yaml
      podTemplate:
        image: ghcr.io/strangelove-ventures/heighliner/chain
        versions:
          - blockHeightStart: 1
            blockHeightEnd: 12345
            version: "v1.0.0"
          - blockHeightStart: 12346
            blockHeightEnd: 23456
            version: "v2.0.0"
```
