### ISSUE TITLE
Rollback support

### ISSUE THREAD

**Issue by danbryan** [strangelove-ventures/cosmos-operator#392]
https://strangeloveventures.slack.com/archives/C05UHA0NGQY/p1700775826667649

would be nice if this was as simple as

```
spec:
  chain:
    rollback: 1804999
    versions:
      - height: 0
        image: ghcr.io/strangelove-ventures/heighliner/dydx:protocol-v1.0.1
      - height: 1805000
        image: ghcr.io/strangelove-ventures/heighliner/dydx:protocol-v2.0.0
```
