### ISSUE TITLE
Log level flag error when set `logLevel: info`

### ISSUE THREAD

**Issue by hakuno2000** [strangelove-ventures/cosmos-operator#422]
In my yaml file, when I set `logLevel: info` like below
```yaml
  chain:
    network: mainnet
    chainID: injective-1
    binary: injectived
    homeDir: .injective
    skipInvariants: true
    genesisURL: "https://snapshots.polkachu.com/genesis/injective/genesis.json"
    snapshotURL: "https://snapshots.polkachu.com/snapshots/injective/injective_73552556.tar.lz4"
    logLevel: info
    logFormat: json
```

then after deploy, I got error log from pod while pod was initing
```
kubectl logs pod/injective-mainnet-0
Defaulted container "node" out of: node, healthcheck, clean-init (init), chain-init (init), genesis-init (init), addrbook-init (init), config-merge (init), snapshot-restore (init), version-check (init)
Error: unknown flag: --log_level
Usage:
  injectived start [flags]
```

Seem like `logLevel` field was translated to flag `--log_level` instead of `--log-level`
Also `logFormat` was translated to flag `--log_format`

**Comment by agouin** [comment]
Instead of setting those values on the chain spec, can you try the `additionalStartArgs`?

E.g.:
```yaml
spec:
  chain:
# ...
    additionalStartArgs:
      - --log-level
      - info
      - --log-format
      - json
# ...
```
