### ISSUE TITLE
privval service should follow replica count

### ISSUE THREAD

**Issue by danbryan** [strangelove-ventures/cosmos-operator#431]
When doing:

```
apiVersion: cosmos.strange.love/v1
kind: CosmosFullNode
metadata:
  name: node
  annotations:
    infra.strange.love/chain: changeme
spec:
  replicas: 1
  ```
  
  cosmos operator deploys
  ```
  changeme-testnet-privval-0
  changeme-testnet-privval-1
  changeme-testnet-privval-2
  ```
  
  Expected behavior is
  ```
  changeme-testnet-privval-0
  ```
