### ISSUE TITLE
CosmosFullnode should allow setting `nodeSelector` on `instanceOverrides`

### ISSUE THREAD

**Issue by nourspace** [strangelove-ventures/cosmos-operator#446]
Currently, cosmos-operator randomly schedules pods. While using `podTemplate.affinity` allows using something like `podAntiAffinity` to avoid scheduling pods on the same node, we want to have the ability to schedule pods on wanted nodes explicitly. This will be part of the existing `instanceOverrides` spec.

Syntax

```yaml
apiVersion: cosmos.strange.love/v1
kind: CosmosFullNode
spec:
  replicas: 3
  type: Sentry
  network: mainnet
  instanceOverrides:
    cosmoshub-sentry-mainnet-1:
      nodeSelector:
        kubernetes.io/hostname: node-1
    cosmoshub-sentry-mainnet-2:
      nodeSelector:
        kubernetes.io/hostname: node-2
    cosmoshub-sentry-mainnet-3:
      nodeSelector:
        kubernetes.io/hostname: node-3
```

```[tasklist]
### AC
- [x] We can schedule for example `cosmos-sentry-cosmoshub-mainnet-1` on a particular node
```
