### ISSUE TITLE
CosmosFullNode allows overriding an individual instance

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/cosmos-operator#91]
Instance is defined as a pod - pvc combo. 

In more detail: Sometimes (like with axelar upgrade) an error happens during the middle of a migration and the data becomes corrupted. So you need to delete the PVC and start over. To fully delete the PVC, the pod bound to it also needs to be deleted. Currently, the Operator won't let you do this. It keeps restoring the PVC and the pod for you. 

This may call for custom PVC overrides per instance as well. 

Roughly, perhaps something like

```yaml
instanceOverrides:
  - 1: # the ordinal, maps to cosmos-fullnode-1 for example
       preventRestart: true # Prevent Operator from restarting if deleted.
       volumeClaimTemplate: {} # PVC overrides for this one instance. 
```
